name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-web:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'
          cache: 'yarn'

      - run: yarn install

      - name: typecheck
        run: yarn tsc --noEmit

      #  Jest encountered an unexpected tokenもんだいで動かなくなった
      # https://zenn.dev/tokiya_horikawa/scraps/75f33067a28292
      # - name: test
      #   run: yarn jest --silent false --verbose false
