name: test

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test-web:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.18.0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - run: pnpm install

      - name: typecheck
        run: pnpm tsc --noEmit

      - name: test
        run: pnpm run test
