name: test

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test-web:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'
          cache: 'yarn'

      - run: yarn install

      - name: typecheck
        run: yarn tsc --noEmit

      - name: test
        run: yarn run vitest -v
